# License AGPL-3.0 or later (http://www.gnu.org/licenses/agpl).

from odoo import api, fields, models


class HelpdeskTicket(models.Model):
    _inherit = "helpdesk.ticket"

    ai_processed = fields.Boolean(
        string="AI Processed",
        default=False,
        help="Has been processed by AI agents"
    )

    ai_classification_confidence = fields.Float(
        string="AI Classification Confidence (%)"
    )

    ai_routing_confidence = fields.Float(
        string="AI Routing Confidence (%)"
    )

    ai_suggestions = fields.Text(
        string="AI Suggestions",
        help="Suggestions generated by AI agents"
    )

    @api.model
    def create(self, vals):
        """Trigger AI processing on ticket creation"""
        ticket = super().create(vals)

        # Check if auto-processing is enabled
        config = self.env['helpdesk.ai.agent.config'].search([], limit=1)
        if config and config.auto_process_new_tickets:
            # Process with AI agents
            self.env['helpdesk.ai.agent'].process_ticket_with_ai(ticket)
            ticket.write({'ai_processed': True})

        return ticket
