# License AGPL-3.0 or later (http://www.gnu.org/licenses/agpl).

from odoo import api, fields, models, _


class HelpdeskTicket(models.Model):
    _inherit = "helpdesk.ticket"

    ai_processed = fields.Boolean(
        string="AI Processed",
        default=False,
        help="Has been processed by AI agents",
        tracking=True,
    )

    ai_classification_confidence = fields.Float(
        string="AI Classification Confidence (%)"
    )

    ai_routing_confidence = fields.Float(
        string="AI Routing Confidence (%)"
    )

    ai_suggestions = fields.Text(
        string="AI Suggestions",
        help="Suggestions generated by AI agents"
    )

    @api.model
    def create(self, vals):
        """Trigger AI processing on ticket creation when auto-process is enabled."""
        ticket = super().create(vals)

        config = self.env['helpdesk.ai.agent.config'].search([], limit=1)
        if config and config.auto_process_new_tickets:
            self.env['helpdesk.ai.agent'].process_ticket_with_ai(ticket)
            ticket.write({'ai_processed': True})

        return ticket

    def action_run_ai_agents(self):
        """Manually trigger AI agent pipeline for this ticket."""
        self.ensure_one()
        self.env['helpdesk.ai.agent'].process_ticket_with_ai(self)
        self.write({'ai_processed': True})
        return {
            'type': 'ir.actions.client',
            'tag': 'display_notification',
            'params': {
                'title': _('AI Agents'),
                'message': _('AI agents have finished processing ticket %s.') % self.number,
                'type': 'success',
                'sticky': False,
            },
        }
